### ISSUE TITLE
SteemCreate Invalid Account Names

### ISSUE THREAD

**Issue by maxwellgerber** [netuoso/steemcreate#1]
# SteemCreate allows for invalid account names

To my knowledge, a valid account name on Steemit starts with a letter, may contain lowercase letters, dashes, or numbers, and ends with a letter or number. It doesn't look like  [SteemCreate](https://www.steemliberator.com/) is properly erroring out on non-alphanumeric characters. 

The following shows an error to the user on the Steemit Account Creation workflow:
![image.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1515271243/qjlkxlzr9r2xmh8h2izl.png)

The same username doesn't show an error to the user on SteemCreate.
![image.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1515271315/qaxvjqjeawuzzylxeo4e.png)

I didn't try to sign up for an invalid account but I can't imagine that would be a good use of $45.

### Thanks for reading!

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@maxg/steemcreate-invalid-account-names">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by netuoso** [comment]
Thanks. Confirmed and fixed with https://github.com/netuoso/steemcreate/commit/c4fbe204a96b2062e4c4dc52d7e9954d53f613d6
